import Banner from "@/components/Banner";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Skills from "@/components/Skills";

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by rafsun",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Navbar />
        </nav>

        <main>
          <Banner />
          <Skills />
          {children}
        </main>
      </body>
    </html>
  );
}
