import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by rafsun",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <ThemeProvider attribute="class"  defaultTheme="light" >
          <nav>
            <Navbar />
          </nav>
          <main>
            {children}
          </main>
          <footer>
            <Footer/>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
